---
title: "Informe de Avance 1"
numbered: true
---
## Problema de investigación - Problema general al especifico. (No tan histórico)
**El argumento del seminario va en torno a la contradiccion conceptual de esfuerzo y talento como concepto de meritocracia, comunmente medida a la part o subestimada hasta el punto de dejar de lado en la medicion de meritocraia**
**El tema general del seminario se orienta a la contradiccion entre dos conceptos Esfuerz y talento, los cuales deben ser tomados de manera diferentes para redistribuir.** 

- Presenta problema, pregunta, hipótesis / argumento central.
- Primer párrafo: tema, objeto de estudio y factores asociados
    - Es crucial, el más importante de la introducción. En base a este párrafo el lector toma la decisión si vale la pena seguir leyendo o no, por eso debe estar dirigido a capturar a la audiencia a la que va dirigido.
    -En general comienza describiendo el tema general y su relevancia social (Ej: La desigualdad económica ha ido en aumento los últimos años, acrecentando las brechas de oportunidades entre los más ricos y los más pobres.) 
    - Es importante recordar que un problema social es distinto de un problema de investigación. No porque existan “altas tasas de suicidio” significa automáticamente que se requiera investigación. El problema a fundamentar en este caso se relacionaría con cómo han sido investigadas las tasas de suicidio, y cómo esta investigación entonces responde a ese problema.
    - Una vez enunciado este tema general, se pasa a la definición del objeto de estudio (Ej: la desigualdad económica se puede definir como …. [citas]).
    - Luego se mencionan los principales elementos/conceptos asociados hasta ahora para explicar el objeto de estudio (Ej: “En la literatura especializada, los principales factores asociados a la desigualdad son la escasez de políticas redistributivas y la corrupción de los gobiernos [citas] ).
    - Cuando se menciona la literatura especializada se recomienda mencionar la perspectiva disciplinar claramente (ej:“desde las investigaciones sociológicas …”)

Chile se ha caracterizado por ser uno de los países más desiguales de América Latina, al mismo tiempo que mantiene uno de los productos internos brutos per cápita más altos de la región [@PNUD_2017]. Esa ambivalencia entre crecimiento y desigualdad remite a preguntas desde la sociología se ha intentado responder sobre cómo las sociedades distribuyen las recompesas y recursos, y bajo qué criterios esas asignaciones de recompensas, beneficios, cargas y recursos son consideradas legítimas o justas [@liebig_sociology_2016]. Así, en las sociedades contemporáneas, la meritocracia se ha consolidado como uno de los principios más extendidos para responder a la pregunta de distribución: las recompensas deben distribuirse según el mérito individual y no según el origen social para orientar la asignación de ingresos, posiciones laborales, oportunidades educativas y acceso a bienes de salud y pensiones [@mijs_unfulfillable_2016; @mulligan_meritocracy_2023a]. Esta asignación de recompensas tiene sentido general, pero no solo organiza distribuciones, sino que legitima desigualdades resultantes al presentarlas como justas o merecidas [@castillo_merit_perc_pref_2019]. Esta doble función de la meritocracia es muy visible en sociedades donde el mercado se ha extendido como el principal organizador de la vida social [@polanyi_1997], y en especial al acceso de bienes sociales a través de la capacidad de pago de las personas [@crouch_et_al_mercantilizacion_europa_2010; @castillo_perceptions_ineq_&_merit_pref_de_justicia_2025, p. 2] y donde el esfuerzo individual es central en la forma en que las personas interpretan sus trayectorias [@araujo_y_martuccelli_soc-chilena_2012, p. 59]. De esta manera la meritocracia se ha entendido originariamente por @young_1964 como la combinación entre esfuerzo más inteligencia (talento). En este sentido, la idea se basa inicialmente en el principio de igualdad de oportunidades, en el cual los individuos a través del esfuerzo y el talento pueden lograr movilidad social y el éxito en ciertas esferas sociales, dejando de lado aspectos no meritorios como el género, clase social, origen familiar, entre otros **[citar definiciones del concepto].** Sin embargo .... 

- Por qué los conceptos se confunden?

- Esto constituye un problema, puesto que en la distribucion de recompenzas se menciona el merito, refiriendo a dos conceptos que son diferntes y contradictorios entre si talentos y logros. Se cae así en una falsa equivalencia. 

- Merecimiento refiere a las formas de reconocimiento que el sujeto puede exigir justamente. El merecimiento no necesita del merito para ser reconocido. porque existen otras formas de reconocimeintoq ue no dependen del merito como lo es el talento o el logro.

## Objeto de estudio

La investigacion tiene como objeto de estudio las preferencias normativas sobre meritocracia diferenciada entre esfuerzo y el talento como criterios de recompensa. 

## Pregunta de investigación
Se plantea la siguiente pregunta de investigación: ¿Difiere la legitimación del esfuerzo y el talento como criterios de recompensa —medida como la brecha entre percepción y preferencia normativa— según la clase social en Chile?

## Revisión inicial de literatura
debate sobre sociedad meritocratica. 

## Propuesta metodológica


## Disponibilidad de datos

Se utilizarán datos de la encuesta Economía moral de la meritocracia y preferencias redistributivas, especificamente la tercera ola del estudio longitudinal desarrollada en Chile en 2020, aplicado mediante Qualtrics a participantes recontactados de olas anteriores. El módulo de meritocracia corresponde a la batería validada en el estudio de castillo_multidimensional_2023a.
N = 1,489.

Se utilizarán datos de la encuesta ISSP (The International Social Survey Programme) especificamente datos del módulo Desigualdad Social V del año 2019.
N = 1,374

Se utilizarán datos de la encuesta ElSOC (Estudio Longitudinal Social de Chile) especificamente datos del módulo ciudadanía y democracia del año 2019.
N = 2,153

**A Revisar** - Medicion del Merit en - International Social Justice Project - European Social Survey, ronda 9 (2018/19), módulo “Justice and Fairness” - General Social Survey (EE.UU.) - World Values Survey 


